Add Jenkinsfile
saic-oss/venus-demo pull request #5
Opened 2020-12-23 00:13 UTC by ac-miller

## what
* Add Jenkinsfile for Jenkins pipeline
* Removed duplicated directories in src/main and src/test
* Added tasks to Taskfile

## why
* We need a Jenkinsfile to run a pipeline automatically when EVTR starts
* We had several duplicated directories that came from renaming the project

2020-12-23 16:18 UTC, ac-miller commented
/test

2020-12-23 16:35 UTC, ac-miller commented
/test

2020-12-23 16:57 UTC, jesse-chauvin submitted a review, later dismissed
Approved

2020-12-24 01:19 UTC, ac-miller commented
/test

2021-01-04 20:47 UTC, Colton-Wrisner submitted a review, later dismissed

2021-01-07 13:24 UTC, ac-miller commented
/test

2021-01-07 14:01 UTC, jesse-chauvin submitted a review, later dismissed
Changes are good.

2021-01-07 14:19 UTC, RothAndrew commented
Every container can't have that much cpu/memory, the pod will never get scheduled. With this config the pod needs 6 cpu and 12 GB of memory

2021-01-07 14:46 UTC, ac-miller commented
The pod does get scheduled through testing, but I see what you mean. I'm going to test with the jnlp and dind containers requesting/limiting minimal cpu and memory.

2021-01-07 15:57 UTC, ac-miller commented
/test

2021-01-07 16:25 UTC, RothAndrew requested changes

2021-01-07 16:25 UTC, RothAndrew commented on Jenkinsfile
> +      imagePullPolicy: Always
Change these to `IfNotPresent`

2021-01-07 16:25 UTC, RothAndrew commented on Jenkinsfile
> +    - name: gitlab-registry-access
This can be removed

2021-01-07 17:05 UTC, RothAndrew approved these changes

2021-01-07 17:07 UTC, ac-miller commented
/test

2021-01-07 17:09 UTC, merged